name: Entrega Contínua

on:
  workflow_call:

jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition Tarefa_API-GO --query taskDefinition > task-definition.json
